language: java
sudo: false
install: true

addons:
    sonarcloud:
        organization: "stepstone-tech"
        token:
            secure: "GgDqkyEwntyerYDdwoTWkJCTDgpeM7ovBbZEwwFpcluTflN1LzKgpjJYkWbyCaMQRSBSxGpiyOpQUN2XKuKtdo/zr/qVowDKRxzf8YiLhaq6mi4/cRHFe1X1mpu8CebIh5pkbUBOsiU4CAwXv5lqdj8AQJHABEWIBZEdFaoCo4CbHeD07bFBwmynOF/yDhpsj6fDJ29qOIMuzlBLCLxzB7bgUvQcCUuNK0ariMB1mxL18USnPNZs1tF8oCVf6LQDz2ctR0nJg9ABhpOFUUPtG56iAKRWq0+GnIcyDvu1hr7kLJUS7RVdlpnjJd1HWVEqq0WL8ACuVJnCsBRHhZJMt9gdm8OZIIR9HNiAbyfhWEFQHZ04sDysgZd0D3G74Zt5KLmS10Zrhn8DCwksFe5E8W0bE4jHGGsPtkWR0/Ra9jR5qGowiQBkmKwhLo7VH1zO+i6mk+uw1gB/qas3Jv81OPNQ9msAc9U5I747QONnYwKdNi85H0tZmkRrrRPV6UYepFF9CUz/O1852bhp8NyT/DB7I0f6raTiG+vT55ACS1VCKa7mlnLPOzAVzhODYYFCNxz09cm9Zhzji5iXm/SIw86lfjOoXWjq9PUr6y6xJB60r6vo/OyG7B2uJsGA4kXiTZ85TPfWRrWYb870ZUxjAIWscCbNL5Brqu2Cz1UqSLw="  
git:
  depth: false

jdk:
    - openjdkjdk8

script:
    - mvn clean test package sonar:sonar -Psonar

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
